services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
  backend:
    build: ./backend
    container_name: flask_container
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://${DB_ROOT_USER}:${DB_ROOT_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin
      LIGHTBOX_API_KEY: ${LIGHTBOX_API_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - app_network
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

volumes:
  mongodb_data:

networks:
  app_network: