services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    env_file:
      - .env
  backend:
    build: ./backend
    container_name: django_container
    restart: always
    depends_on:
      - mongodb
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_ROOT_USER}
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app_network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env

volumes:
  mongodb_data:

networks:
  app_network: